services:
  ml-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: paperai_ml-backend_c
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
          - PYDEVD_DISABLE_FILE_VALIDATION=1
          - PYTHONUNBUFFERED=1
    command: >
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678
      -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: paperai_frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:18.1-alpine3.21
    container_name: paperai_postgres_c
    environment:
      - POSTGRES_DB=paperai_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d paperai_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
